[package]
name = "file_rw"
version = "0.1.3"
edition = "2021"
description = "A library for high-performance, memory-mapped file I/O utilities."
categories = ["concurrency", "filesystem", "Rust Patterns"]
authors = ["Adam Killam <adammkillam@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/amkillam/file_rw"

[dependencies]
digest = { version = "0.10.7", features = ["core-api"] }
filepath = "0.1.2"
memmap2 = "0.9.3"
rayon = "1.8.0"
sha3 = "0.10.8"
