[package]
name = "file_rw"
version = "0.2.0"
edition = "2021"
description = "A library for high-performance, memory-mapped file I/O utilities."
categories = ["concurrency", "filesystem", "rust-patterns"]
authors = ["Adam Killam <adammkillam@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/amkillam/file_rw"

[dependencies]
ahash = "0.8.6"
digest = { version = "0.10.7", features = ["core-api"] }
filepath = "0.1.1"
memmap2 = "0.9.3"
rayon = "1.8.0"
sha3 = "0.10.8"

[dev-dependencies]
tempfile = "3.8.1"
test_utils = { path = "test_utils"}
